# Generated by Django 3.2 on 2021-04-25 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_transaction_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='Transactions',
        ),
        migrations.RenameModel(
            old_name='Wallet',
            new_name='Wallets',
        ),
    ]
