# Generated by Django 3.2 on 2021-04-27 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_auto_20210425_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallets',
            name='balance',
        ),
    ]
